package plugin

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/mmcdole/runes/internal/config"
	"github.com/mmcdole/runes/internal/util"
)

type PluginEvent int

const (
	ProxyConnectEvent PluginEvent = iota
	ProxyDisconnectEvent
)

type BufferOutput struct {
	Line       string
	BufferName string
}

func NewPluginEngine(logger util.Logger, conf *config.Config) *PluginEngine {
	return &PluginEngine{
		InCommandChan:   make(chan string),
		InTextLineChan:  make(chan string),
		OutSendChan:     make(chan string),
		OutCommandChan:  make(chan string),
		OutTextLineChan: make(chan BufferOutput),
		plugins:         []*Plugin{},
		logger:          logger,
		config:          conf,
	}
}

type PluginEngine struct {
	// Receive command from a client
	// Note: check and execute aliases that match the input command
	InCommandChan chan string

	// Receive line of text from server
	// Note: check for actions/triggers, highlights, replacements, hides
	InTextLineChan chan string

	// Output commands that weren't handled by plugin engine
	// Note: forward commands to the server that weren't an alias
	OutCommandChan chan string

	// Output commands generated by the plugin engine
	// Note: calls to send() from plugins need to be processed from the start
	OutSendChan chan string

	// Output text line(s) to that have been processed
	// Note: forward text lines and plugin output to the client buffers
	OutTextLineChan chan BufferOutput

	plugins []*Plugin
	logger  util.Logger
	config  *config.Config
}

func (pe *PluginEngine) Start() {
	pe.logger.Debug("[PluginEngine]: Started")

	err := pe.loadOrCreateDefaultPlugin()
	if err != nil {
		pe.logger.Error("Failed to create or load default plugin: %v", err)
		return
	}

	for {
		select {
		case command := <-pe.InCommandChan:
			pe.handleCommand(command)
		case line := <-pe.InTextLineChan:
			pe.handleTextLine(line)
		}
	}
}

func (pe *PluginEngine) loadOrCreateDefaultPlugin() error {
	defaultPath := filepath.Join(pe.config.ConfigDir, "init.lua")

	// Check if default plugin exists and create empty one if it doesn't
	if _, err := os.Stat(defaultPath); os.IsNotExist(err) {
		file, err := os.Create(defaultPath)
		if err != nil {
			return err
		}
		defer file.Close()
	}

	// Load the default plugin
	defaultPlugin := NewPlugin("default", defaultPath, pe)
	pe.plugins = append(pe.plugins, defaultPlugin)
	err := defaultPlugin.Load()
	if err != nil {
		return err
	}

	return nil
}

func (pe *PluginEngine) handleCommand(command string) {
	// TODO: process commands and check against alias list
	pe.logger.Trace("[PluginEngine]: Command In: %s", strings.TrimSpace(command))

	// TODO: Process Commands/check for aliases
	handledAlias := false
	for _, plugin := range pe.plugins {
		if executed := plugin.CheckAndExecuteAlias(command); executed {
			handledAlias = handledAlias || executed
		}
	}

	if handledAlias {
		pe.logger.Trace("[PluginEngine]: Command Matched Alias: %s", strings.TrimSpace(command))
	} else {
		pe.logger.Trace("[PluginEngine]: Command Out (Passthrough): %s", strings.TrimSpace(command))
		pe.OutCommandChan <- command
	}
}

func (pe *PluginEngine) handleTextLine(line string) {
	pe.logger.Trace("[PluginEngine]: Text In: %s", strings.TrimSpace(line))

	// TODO: process text line, check for actions/triggers/subs/highlights

	pe.logger.Trace("[PluginEngine]: Text Out: %s", strings.TrimSpace(line))

	// Don't specify buffer to make it "primary"
	pe.OutTextLineChan <- BufferOutput{Line: line}
}

func (pe *PluginEngine) handlePluginSend(cmd string) {
	pe.logger.Trace("[PluginEngine]: Command Out (Send): %s", strings.TrimSpace(cmd))
	pe.OutSendChan <- cmd
}
