package plugin

type TextLineOutput struct {
	Line   string
	Buffer string
}

type PluginEngine struct {
	// Receive command from a client
	// Note: check and execute aliases that match the input command
	InCommandChan chan string

	// Receive line of text from server
	// Note: check for actions/triggers, highlights, replacements, hides
	InTextLineChan chan string

	// Output commands that weren't handled by plugin engine
	// Note: forward commands to the server that weren't an alias
	OutCommandChan chan string

	// Output commands generated by the plugin engine
	// Note: calls to send() from plugins need to be processed from the start
	OutSendChan chan string

	// Output text line(s) to that have been processed
	// Note: forward text lines and plugin output to the client buffers
	OutTextLineChan chan TextLineOutput
}
