-- vk.lua


-- Repeat command handler
alias.add("^[/#](%d+)%s+(.+)$", function(matches, line)
    local count = tonumber(matches[1])
    local command = matches[2]
    if count > 0 then
        runes.send(string.rep(command .. ";", count):sub(1, -2))
    end
end)

alias.add("^(%d+)([nsewud][ew]?)$", function(matches, line)
    local count, dir = tonumber(matches[1]), matches[2]
    runes.send(string.rep(dir .. ";", count):sub(1, -2))
end)

-- Viking Mud Speedpaths;


-- *** Global Larstown ***;

alias.exact("2sword!", "s;2e;n;9e;n")
alias.exact("2sword", "s;9w;s;2w;n")
alias.exact("7scroll", "s;w;w;w;w;w;w;w;w;w;w;w;w;n;n;n;e;ne;ne;se;nw;sw;sw;w;n;n;move stone;s;s;e;ne;ne;se;nw;sw;sw;w;s;s;s;e;e;e;e;e;e;e;e;e;e;e;e;n")
alias.exact("altar!", "s;3e;n")
alias.exact("altar", "s;3w;n")
alias.exact("animal!", "s;e;d;out;s;e;n;e;n")
alias.exact("animal", "s;w;s;w;n;in;u;w;n;dust lamp;kill animal")
alias.exact("aqueen!", "5e;d;n;se;se;e;3s;2e;rope-shaft!")
alias.exact("aqueen", "rope-shaft;2w;3n;w;nw;nw;s;u;w;search plants;#7 search plants;4w")
alias.exact("arena!", "2s;4e")
alias.exact("arena", "4w;2n")
alias.exact("armyg!", "2w;n;open gate;2n;e;ne;4e;s;7e;n")
alias.exact("armyg", "s;7w;n;4w;sw;w;s;open gate;2s;2e")
alias.exact("ashmon!", "w;w;2s;sw;3e;mguards!")
alias.exact("ashmon", "mguards;3w;ne;2n;e;ne")
alias.exact("atli!", "9e;s;10e;2e;n")
alias.exact("atli", "s;10w;10w;2s;3w")
alias.exact("bank!", "w;n;e;n")
alias.exact("bank", "s;w;s;e")
alias.exact("bard!", "2e;s;2d;6s;7e;n")
alias.exact("bard", "s;7w;6n;2u;n;2w")
alias.exact("bdp!", "7e;n")
alias.exact("bdp", "s;7w")
alias.exact("belanna!", "n;out;3w;enter flowers;ghost!")
alias.exact("belanna", "ghost;enter bushes;3e;enter;s")
alias.exact("bigd!", "e;7s;2w;3s;7e;n")
alias.exact("bigd", "s;7w;3n;2e;7n;w")
alias.exact("bkgolem!", "d;move carpet;2n;u;w;s;e;2s;2d;6s;7e;n")
alias.exact("bkgolem", "s;w;w;w;w;w;w;w;n;n;n;n;n;n;u;u;n;w;n;e;roll boulder;pull ring;d;pull ring;d;2s;u")
alias.exact("blood!", "e;u;u;u;u;u;u;w;s;e;n")
alias.exact("blood", "s;w;n;e;d;d;d;d;d;d;w")
alias.exact("bluedragon!", "w;n;w;nw;w;w;w;w;s;climb;s;s;s;s;se;s;s;s;e;n")
alias.exact("bluedragon", "s;w;n;n;n;nw;n;n;n;n;enter;n;e;e;e;se;e;s;e")
alias.exact("bthief!", "sw;s;s;se;3e;ne;n;n;nw;4n;open gate;10n;w;w;cassius!")
alias.exact("bthief", "cassius;2e;9s;open gate;5s;se;s;s;sw;3w;nw;n;n;ne")
alias.exact("cards", "s;e;4n;5e;cross arms;get cards;5w;4s;w;n")
alias.exact("cassius!", "e;e;n;n;open gate;n;e;ne;e;e;e;e;s;e;e;e;e;e;e;e;n")
alias.exact("cassius", "s;w;w;w;w;w;w;w;n;w;w;w;w;sw;w;s;open gate;s;s;w;w")
alias.exact("cat!", "out;s;w;s;se;e;2s;9e;n")
alias.exact("cat", "s;9w;2n;w;nw;n;e;n;enter")
alias.exact("chang!", "out;se;s;e;5s;5e;n")
alias.exact("chang", "s;5w;5n;w;n;nw;enter")
alias.exact("child!", "out;w;w;s;s;s;e;e;e;e;e;n")
alias.exact("child", "s;w;w;w;w;w;n;n;n;e;e;enter")
alias.exact("citadel!", "n;w;w;w;w;s;w;w;s;s;s;s;s;s;w;n")
alias.exact("citadel", "s;e;n;n;n;n;n;n;e;e;n;e;e;e;e;s")
alias.exact("cobble", "s;3e;n;get all;s;3w;n")
alias.exact("cone!", "hel-flugeluff!")
alias.exact("cone", "hel-flugeluff")
alias.exact("dacian!", "sw;sw;sw;s;sw;sw;ne;e;se;4s;w;2s;3w;n")
alias.exact("dacian", "s;3e;2n;e;4n;nw;w;sw;ne;ne;n;ne;ne;ne")
alias.exact("dchief!", "n;n;w;w;u;u;u;u;4s;w;n")
alias.exact("dchief", "s;e;4n;d;d;d;d;e;e;s;s")
alias.exact("deathk!", "n;e;climb;s;s;s;s;se;s;s;s;e;n")
alias.exact("deathk", "s;w;n;n;n;nw;n;n;n;n;enter;w;s")
alias.exact("deep!", "s;u;w;2n;w;2d;enter;bdp!")
alias.exact("deep", "bdp;enter;2u;e;2s;e;d;enter cell 2")
alias.exact("dino!", "s;s;s;s;s;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;n")
alias.exact("dino", "s;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;n;n;n;n;n")
alias.exact("disciples!", "s;se;s;w;s;w;2s;7e;n")
alias.exact("disciples", "s;7w;2n;e;n;e;n;nw;n")
alias.exact("dleader!", "fro-dleader!")
alias.exact("dleader", "fro-dleader")
alias.exact("draco!", "u;u;n;n;n;n;n;n;n;n;n;e;e;n;e;e;n;e;e;e;e;e;e;e;e;e;n")
alias.exact("draco", "s;w;w;w;w;w;w;w;w;w;s;w;w;s;w;w;s;s;s;s;s;s;s;s;s;d;d")
alias.exact("dracul!", "s;s;utter gold;s;s;utter water;s;s;s;s;d;d;d;w;w;s;s;s;s;s;e;e;e;e;e;e;e;n")
alias.exact("dracul", "s;w;w;w;w;w;w;w;n;n;n;n;n;e;e;u;u;u;n;n;enter;n;n;utter water;n;n;utter gold;n;n")
alias.exact("druidleader!", "u;s;u;w;s;out;s;s;s;s;s;s;s;e;e;e;e;s;se;s;s;s;s;s;w;n")
alias.exact("druidleader", "s;e;n;n;n;n;n;nw;n;w;w;w;w;n;n;n;n;n;n;n;enter;n;e;open door;d;n;d")
alias.exact("dwarf2!", "n;2w;4u;4s;w;n")
alias.exact("dwarf2", "s;e;4n;4d;2e;s")
alias.exact("dwarf3!", "3w;u;9s;7e;n")
alias.exact("dwarf3", "s;7w;9n;tie rope to ring;2d;3e")
alias.exact("dwarfleader!", "2w;n;w;2n;2w;5s;8e;n")
alias.exact("dwarfleader", "s;8w;5n;2e;2s;e;s;2e")
alias.exact("dwarfs!", "n;2n;2w;4s;8e;n")
alias.exact("dwarfs", "s;8w;5n;2e;3s")
alias.exact("egs!", "fer-egs!")
alias.exact("egs", "fer-egs")
alias.exact("elfs!", "d;open door;out;n;7e;n")
alias.exact("elfs", "s;7w;s;open door;in;u")
alias.exact("ent!", "5w;7s;ecity;empire!")
alias.exact("entrecote!", "s;2e;n;9e;n")
alias.exact("entrecote", "s;9w;s;2w;n")
alias.exact("ent", "empire;ecity!;7n;5e")
alias.exact("ethilrist!", "s;3e;2s;7e;5s;7e;n")
alias.exact("ethilrist", "s;7w;5n;7w;2n;3w;n")
alias.exact("eugene!", "tio-eugene!")
alias.exact("eugene", "tio-eugene")
alias.exact("fb!", "w;s;e;n")
alias.exact("fb", "s;w;n;e")
alias.exact("fcat!", "out;s;w;s;se;e;2s;9e;n")
alias.exact("fcat", "s;9w;2n;w;nw;n;e;n;enter")
alias.exact("ffox!", "e;2s;2w;s;4e;s;sw;se;3e;s;9e;n")
alias.exact("ffox", "s;9w;n;3w;nw;ne;n;4w;n;2e;2n;w")
alias.exact("firefiend!", "s;u;w;2n;w;2d;enter;bdp!")
alias.exact("firefiend", "bdp;enter;2u;e;2s;e;d;enter cell 1")
alias.exact("flint!", "ne;3n;nw;s;mirror!")
alias.exact("frank!", "d;in;e;d;3n;e;n;e;n")
alias.exact("frank", "s;w;s;w;3s;u;w;open window;out;u")
alias.exact("fry!", "n;u;9n;2e;n;2e;n;9e;n")
alias.exact("fry", "s;9w;s;2w;s;2w;9s;d;s")
alias.exact("ftemple!", "s;s;s;w;sw;s;s;se;s;sw;se;e;e;e;s;e;e;e;e;e;e;e;e;e;n")
alias.exact("ftemple", "s;w;w;w;w;w;w;w;w;w;n;w;w;w;nw;ne;n;nw;n;n;ne;e;n;n;n")
alias.exact("galv!", "n;5e;ne;4n;ne;ne;ne;3n;ne;ne;ne;10n;3n;4e;n")
alias.exact("galv", "s;4w;10s;3s;sw;sw;sw;3s;sw;sw;sw;4s;sw;5w;s")
alias.exact("gaunts!", "out;w;nw;open door;inside;d;3w;u;se;out;e;2n;2e;2s;4e;s;2e;3s;7e;n")
alias.exact("gaunts", "s;7w;3n;2w;n;4w;2n;2w;2s;w;enter;nw;move branch;3e;u;open door;outside;se;e;enter")
alias.exact("gems!", "2u;s;out;2s;e;n;siam!")
alias.exact("gems", "siam;s;w;2n;enter;n;2d")
alias.exact("gflask!", "d;e;e;e;s;e;e;e;e;e;e;e;n")
alias.exact("gflask", "s;w;w;w;w;w;w;w;n;w;w;w;climb tree;move mirror;n;pull lever;n;get flask")
alias.exact("ghirma!", "out;s;s;e;e;s;e;e;e;e;e;e;e;n")
alias.exact("ghirma", "s;w;w;w;w;w;w;w;n;w;w;n;n;enter")
alias.exact("ghost!", "w;ne;enter;sisters!")
alias.exact("ghost", "sisters;out;sw;e")
alias.exact("glom!", "2s;e;2s;e;s;siam!")
alias.exact("glom", "siam;s;w;2n;w;2n")
alias.exact("gmafmer!", "2s;se;s;sw;rose!")
alias.exact("gmafmer", "rose;ne;n;nw;2n")
alias.exact("gnome!", "w;s;s;s;s;s;w;w;s;s;s;e;e;e;e;e;e;e;n")
alias.exact("gnomelift!", "exit;w;2s;2w;6s;w;n")
alias.exact("gnomelift", "s;e;6n;2e;2n;e;enter lift")
alias.exact("gnome", "s;w;w;w;w;w;n;n;n;n;n;w;n;nw;enter;out;se;s;w;n;n;enter;n;d;d")
alias.exact("golem!", "sw;5s;w;s;w;2s;7e;n")
alias.exact("golem", "s;7w;3n;2e;5n;e")
alias.exact("goose", "climb stalk;3u;n;e;n;ne;e;n;u;take pillow;take pillow;d;s;e;give pillow to giant;give pillow to giant;close curtains;take lever from giant;2w;sw;s;w;2s;e;take corn;2w;sw;put lever in hole;pull lever;enter;give corn to goose;exit;ne;e;w;sw;enter;exit;ne;e;w;sw;enter;take all;exit;nw;e;n;5d")
alias.exact("gord!", "s;se;e;2s;sw;4w;n")
alias.exact("gord", "s;4e;ne;2n;w;move branch;n")
alias.exact("hag!", "out;se;s;se;se;s;sw;rose!")
alias.exact("hag", "rose;ne;n;nw;nw;n;nw;move bush;enter")
alias.exact("ham!", "e;3s;6w;s;2w;6s;w;n")
alias.exact("ham", "s;e;6n;2e;n;6e;3n;w")
alias.exact("hguard!", "4s;sw;4w;n")
alias.exact("hguard", "s;4e;ne;4n")
alias.exact("hpriest!", "e;s;se;s;e;s;e;s;s;e;e;e;e;e;e;e;n")
alias.exact("hpriest", "s;w;w;w;w;w;w;w;n;n;w;n;w;n;nw;n;w")
alias.exact("hue!", "s;s;e;ne;ne;se;nw;sw;sw;w;s;s;s;e;e;e;e;e;e;e;e;e;e;e;e;n")
alias.exact("hue", "s;w;w;w;w;w;w;w;w;w;w;w;w;n;n;n;e;ne;ne;se;nw;sw;sw;w;n;n;")
alias.exact("hydra!", "5w;push button;3n;out;2e;n;3e;n")
alias.exact("hydra", "s;3w;s;2w;sw;3s;press;4e")
alias.exact("iceboltwand!", "5n;2e;n;2e;n;9e;n")
alias.exact("iceboltwand", "s;9w;s;2w;s;2w;5s")
alias.exact("icedragon!", "3s;w;2n;w;push button;3n;out;2e;n;3e;n")
alias.exact("icedragon", "s;3w;s;2w;sw;3s;push button;e;2s;e;3n")
alias.exact("icon!", "e;e;e;se;e;s;s;s;e;e;s;s;s;s;s;e;e;e;e;e;e;e;n")
alias.exact("icon", "s;w;w;w;w;w;w;w;n;n;n;n;n;w;w;n;n;n;w;nw;w;w;w")
alias.exact("kbag!", "e;n;n;n;w;w;e;e;n;n;open gate;n;e;ne;e;e;e;e;s;e;e;e;e;e;e;e;n")
alias.exact("kbag", "s;w;w;w;w;w;w;w;n;w;w;w;w;sw;w;s;open gate;s;s;w;w;e;e;s;s;s;w")
alias.exact("kbank!", "n;e;n;w;w;e;e;n;n;open gate;n;e;ne;e;e;e;e;s;e;e;e;e;e;e;e;n")
alias.exact("kbank", "s;w;w;w;w;w;w;w;n;w;w;w;w;sw;w;s;open gate;s;s;w;w;e;e;s;w;s")
alias.exact("kender!", "s;ne;sw;4s;se;2s;climb;4s;se;3s;e;n")
alias.exact("kender", "s;w;3n;nw;4n;enter;2n;nw;4n;ne;sw;n")
alias.exact("khan!", "s;e;e;se;s;s;s;s;e;se;s;s;s;s;w;s;s;w;w;w;n")
alias.exact("khan", "s;e;e;e;n;n;e;n;n;n;n;nw;w;n;n;n;n;nw;w;w;n")
alias.exact("killroy", "s;w;w;w;w;w;w;w;n;n;d")
alias.exact("kimrea!", "3e;d;s;sisters!")
alias.exact("kimrea", "sisters;n;u;3w")
alias.exact("kitchen!", "e;s;2e;3s;2w;sw;4s;w;s;w;2s;7e;n")
alias.exact("kitchen", "s;7w;2n;e;n;e;4n;ne;2e;3n;2w;n;w")
alias.exact("kitiara!", "w;w;nw;w;w;w;w;s;climb;s;s;s;s;se;s;s;s;e;n")
alias.exact("kitiara", "s;w;3n;nw;4n;enter;n;3e;se;2e")
alias.exact("kodiac!", "out;w;sw;3w;5s;se;4s;w;2s;3w;n")
alias.exact("kodiac", "s;3e;2n;e;4n;nw;5n;3e;ne;e;enter")
alias.exact("koja!", "nw;sw;sw;w;3s;10e;2e;n")
alias.exact("koja", "s;10w;2w;3n;e;ne;ne;se")
alias.exact("korlok!", "w;n;ne;e;ne;ne;ne;e;e;e;e;e;e;e;e;e;e;e;n")
alias.exact("korlok", "s;w;w;w;w;w;w;w;w;w;w;w;sw;sw;sw;w;sw;s;e")
alias.exact("kotro!", "dan-kotro!")
alias.exact("kotro", "dan-kotro")
alias.exact("kpotion!", "n;e;n;n;open gate;n;e;ne;e;e;e;e;s;e;e;e;e;e;e;e;n")
alias.exact("kpotion", "s;w;w;w;w;w;w;w;n;w;w;w;w;sw;w;s;open gate;s;s;w;s")
alias.exact("lager!", "d;2e;d;out;s;e;n;e;n")
alias.exact("lager", "s;w;s;w;n;in;u;2w;u")
alias.exact("lake!", "ne;e;ne;e;ne;e;ne;ne;ne;10e;e;n")
alias.exact("lake", "s;10w;w;sw;sw;sw;w;sw;w;sw;w;sw")
alias.exact("lashdeem!", "se;se;e;ne;ne;ne;e;ne;e;ne;e;ne;ne;ne;e;10e;n")
alias.exact("lashdeem", "s;10w;w;sw;sw;sw;w;sw;w;sw;w;sw;sw;sw;w;nw;nw")
alias.exact("leather!", "okj-leather!")
alias.exact("leather", "okj-leather")
alias.exact("lguard!", "3d;out;3n;2e;ne;4w;n")
alias.exact("lguard", "s;4e;sw;2w;3s;enter;3u")
alias.exact("lieutenant!", "s;w;3d;enter;bdp!")
alias.exact("lieutenant", "bdp;enter;2u;e;n;push button")
alias.exact("log!", "n;4w;3s;w;n")
alias.exact("log2!", "move patch;e;move patch;e;2n;nw;n;w;w;n")
alias.exact("log2", "s;2e;s;se;s;exa bush;s;move patch;w;move patch;w;get log")
alias.exact("log", "s;e;3n;4e;s")
alias.exact("luci!", "fro-luci!")
alias.exact("luci", "fro-luci")
alias.exact("mage!", "d;2n;10e;n")
alias.exact("mage", "s;10w;2s;u")
alias.exact("max!", "e;s;s;s;w;s;s;w;w;w;n")
alias.exact("max", "s;e;e;e;n;n;e;n;n;n;w")
alias.exact("mith", "leather;exit;s;go through the forest;field;dig ground")
alias.exact("mith!", "house;se;sw;leather!")
alias.exact("mguards!", "6w;5s;se;4s;w;2s;3w;n")
alias.exact("mguards", "s;3e;2n;e;4n;nw;5n;6e")
alias.exact("mirror!", "climb;4s;se;3s;e;n")
alias.exact("mirror", "s;w;3n;nw;4n;enter")
alias.exact("mk!", "4s;out;2e;out;n;3e;n")
alias.exact("mking!", "s;se;sw;sw;s;s;s;s;s;s;s;s;w;w;s;s;s;e;e;e;e;e;e;e;n")
alias.exact("mking", "s;w;w;w;w;w;w;w;n;n;n;e;e;n;n;n;n;n;n;n;wimpy 0;n;wimpy 90;ne;ne;n")
alias.exact("mk", "s;3w;s;enter;2w;shrink;4n")
alias.exact("moose!", "nw;sw;2s;e;s;eugene!")
alias.exact("moose", "eugene;n;w;2n;ne;se")
alias.exact("moss", "s;e;e;e;n;n;e;e;e;e;e;e;n;n;w;w;w;remove moss;e;e;e;s;s;w;w;w;w;w;w;s;s;w;w;w;n")
alias.exact("mother!", "roo-mother!")
alias.exact("mother", "roo-mother")
alias.exact("mroth!", "out;s;e;s;out;6s;se;4s;w;2s;3w;n")
alias.exact("mroth", "s;3e;2n;e;4n;nw;6n;enter;n;w;n;enter")
alias.exact("napp!", "e;e;n;w;e;s;s;w;w;s;e;e;e;e;s;sw;se;e;e;e;s;e;e;e;e;e;e;e;e;e;n")
alias.exact("napp", "s;w;w;w;w;w;w;w;w;w;n;w;w;w;nw;ne;n;w;w;w;w;n;e;e;n;n;w;e;s;w;w")
alias.exact("necrog!", "exit;2s;w;3s;7e;mguards!;wield all")
alias.exact("necrog", "unwield all;mguards;7w;3n;e;2n;enter")
alias.exact("nefer!", "ano-nefer!")
alias.exact("nefer", "ano-nefer")
alias.exact("nest!", "2s;sw;8w;2s;3w;n")
alias.exact("nestor!", "2s;sw;8w;2s;3w;n")
alias.exact("nestor", "s;3e;2n;8e;ne;n;n")
alias.exact("nest", "s;7w;s;u;e;enter nest")
alias.exact("nguild!", "exit;s;s;w;s;s;s;e;s;s;s;s;se;s;s;s;s;s;w;s;s;w;w;w;n")
alias.exact("nguild", "unwield all;s;e;e;e;n;n;e;n;n;n;n;n;nw;n;n;n;n;w;n;n;n;e;n;n;enter;wield all")
alias.exact("nif!", "travel larstown")
alias.exact("nif", "s;2w;n;travel nif")
alias.exact("noekken!", "s;s;s;s;e;e;e;e;n")
alias.exact("noekken", "s;w;w;w;w;n;n;n;n")
alias.exact("nun!", "e;out;s;w;s;se;e;2s;9e;n")
alias.exact("nun", "s;9w;2n;w;nw;n;e;n;enter;w")
alias.exact("nutra!", "e;s;2e;3s;2w;sw;5s;w;s;w;2s;7e;n")
alias.exact("nutra", "s;7w;3n;2e;5n;3e;3n;2w;n;w")
alias.exact("ogres!", "w;n;ne;e;ne;ne;ne;e;10e;n")
alias.exact("ogres", "s;10w;w;sw;sw;sw;w;sw;s;e")
alias.exact("onen!", "3w;sw;4w;8s;w;n")
alias.exact("onen", "s;e;8n;4e;move leaves;ne;3e")
alias.exact("onylair!", "elair!;ecity;empire!")
alias.exact("onylair", "empire;ecity!;elair")
alias.exact("orcs!", "s;10e;n")
alias.exact("orcs", "s;10w;n")
alias.exact("ox!", "s;n;2s;e;2s;4e;n")
alias.exact("ox", "s;4w;2n;w;3n;s")
alias.exact("paladin!", "2s;2e;3s;open gate;10e;s;10e;2e;n")
alias.exact("paladin", "s;10w;7w;2s;2w;2n;2w;open gate;w;3n;2w;2n")
alias.exact("pan!", "open trapdoor;u;enter portal;d;e;out;e;e;s;s;e;s;s;e;e;s;s;s;s;s;e;e;e;e;e;n")
alias.exact("pan", "s;w;w;w;w;w;n;n;n;n;n;w;w;n;n;w;n;n;w;w;enter;w;w;climb tree;enter portal;open trapdoor")
alias.exact("pecker!", "out;nw;w;3s;10e;2e;n")
alias.exact("pecker", "s;10w;2w;3n;e;se;climb trunk")
alias.exact("pguild!", "s;s;w;w;s;s;s;s;e;e;e;e;n;open gate;e;e;e;e;e;e;e;e;e;s;e;e;e;e;e;e;e;e;e;e;e;e;e;n")
alias.exact("pguild", "s;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;s;s;w;w;w;open gate;w;n;n;n;w;w;n;n")
alias.exact("pile!", "n;5e;ne;4n;ne;ne;ne;3n;ne;ne;ne;10n;n;n;n;4e;n")
alias.exact("pile", "s;4w;10s;3s;sw;sw;sw;s;s;s;sw;sw;sw;4s;sw;5w;s")
alias.exact("pizza!", "e;3n;3w;4u;4s;w;n")
alias.exact("pizza", "s;e;4n;4d;3e;3s;w")
alias.exact("player!", "2w;d;out;s;e;n;e;n")
alias.exact("player", "s;w;s;w;n;in;u;2e")
alias.exact("poolplayer!", "2w;d;out;s;e;n;e;n")
alias.exact("poolplayer", "s;w;s;w;n;in;u;2e")
alias.exact("pot!", "u;4s;w;3s;2w;2s;2w;3s;7e;n")
alias.exact("potion!", "open door;n;3e;n;open gate;10e;s;10e;2e;n")
alias.exact("potion", "s;7w;3n;2e;5n;3e;4n;d")
alias.exact("pot", "s;7w;3n;2e;2n;2e;3n;e;4n;d")
alias.exact("premier!", "n;n;w;d;d;enter portal;7e;n")
alias.exact("premier", "s;7w;enter portal;u;u;e;s;s")
alias.exact("priestess!", "w;u;w;n;n;w;d;d;enter;e;e;e;e;e;e;e;n")
alias.exact("priestess", "s;w;w;w;w;w;w;w;enter;u;u;e;s;s;e;d;enter cell 3")
alias.exact("ptower!", "w;s;s;w;w;s;s;s;s;s;s;w;n")
alias.exact("ptower", "s;e;n;n;n;n;n;n;e;e;n;n;e")
alias.exact("rauros!", "2s;enter boat;3w;n")
alias.exact("rauros", "s;3e;enter boat;2n")
alias.exact("redkey", "s;w;w;w;w;w;w;w;w;w;w;w;w;n;n;n;e;ne;ne;se;nw;sw;sw;se;drop pizza;drop pizza;drop pizza;enter waterfall;e;move rock;get key;w;out;take all;nw;ne;ne;se;nw;sw;sw;w;s;s;s;e;e;e;e;e;e;e;e;e;e;e;e;n")
alias.exact("reidar!", "ereidar!;empire!")
alias.exact("reidar", "empire;ereidar")
alias.exact("romanfort!", "e;3s;w;2s;3w;n")
alias.exact("romanfort", "s;3e;2n;e;3n;w")
alias.exact("rope-shaft!", "u;9s;7e;n")
alias.exact("rope-shaft", "s;7w;9n;#3 untie rope;#3 get rope;9s;w;4n;2e;s;3e;#3 drop rope;exa hooks;get rope;3w;n;2w;4s;e;9n;tie rope to ring;d;d")
alias.exact("rose!", "ne;se;s;sw;8e;mguards!")
alias.exact("rose", "mguards;8w;ne;n;nw;sw")
alias.exact("ruin!", "out;se;s;se;5s;2e;se;3e;2s;2w;s;4e;s;sw;se;3e;s;9e;n")
alias.exact("ruin", "s;9w;n;3w;nw;ne;n;4w;n;2e;2n;3w;nw;2w;5n;nw;n;nw;enter")
alias.exact("runeg!", "u;out;n;5e;5s;se;4e;n;6e;10e;10e;2s;w;n")
alias.exact("runeg", "s;e;2n;10w;10w;6w;s;4w;nw;5n;5w;s;enter;d")
alias.exact("sabre!", "n;n;n;n;n;n;n;n;w;n;e;e;n;e;e;e;e;e;e;e;e;e;n")
alias.exact("sabre", "s;w;w;w;w;w;w;w;w;w;s;w;w;s;e;s;s;s;s;s;s;s;s")
alias.exact("samg!", "d;3s;4e;5s;7e;n")
alias.exact("samg!", "d;3s;4e;5s;7e;n")
alias.exact("samg", "s;7w;5n;4w;3n;u")
alias.exact("samg", "s;7w;5n;4w;3n;u")
alias.exact("samurais!", "2s;samg!")
alias.exact("samurais", "samg;2n")
alias.exact("santa!", "u;w;d;open window;in;e;d;n;n;n;e;n;e;n")
alias.exact("santa", "s;w;s;w;s;buy ticket;s;s;u;w;open window;out;u;e;d")
alias.exact("scelguard!", "7n;w;n")
alias.exact("scelguard", "s;e;7s")
alias.exact("sdragon!", "e;e;climb;s;s;s;s;se;s;s;s;e;n")
alias.exact("sdragon", "s;w;n;n;n;nw;n;n;n;n;enter;w;w")
alias.exact("serpent!", "2n;2w;u;ashore;4w;n")
alias.exact("serpent", "s;4e;enter ship;d;pull;2n;e;3s")
alias.exact("seth!", "s;10s;7e;5s;7e;n")
alias.exact("seth", "s;7w;5n;7w;10n;n")
alias.exact("shade!", "u;w;ashore;2w;2s;4u;8w;2s;3w;n")
alias.exact("shade", "s;3e;2n;8e;4d;3n;2e;enter ship;e;d")
alias.exact("shagul!", "out;n;nw;sw;s;w;w;sw")
alias.exact("shagul", "n;w;w;nw;n;move ferns;ne;e;e;n;ne;se;s")
alias.exact("siam!", "s;e;5s;5e;n")
alias.exact("siam", "s;5w;5n;w;n")
alias.exact("silverfox!", "3s;2w;s;4e;s;SW;SE;3e;s;9e;n")
alias.exact("silverfox", "s;9w;n;3w;NW;NE;n;4w;n;2e;3n")
alias.exact("sisters!", "out;sw;2s;se;5s;w;n")
alias.exact("sisterstuff", "sisters;n;2w;take all;e;s;d;ne;take all;sw;u;e;sisters!")
alias.exact("sisters", "s;e;5n;nw;2n;ne;enter")
alias.exact("skeletons!", "exit;e;2n;2w;2s;w;3n;n;w;n")
alias.exact("skeletons", "s;e;3s;e;2n;2e;2s;w;enter")
alias.exact("slavic!", "ne;e;se;4s;w;2s;3w;n")
alias.exact("slavic", "s;3e;2n;e;4n;nw;w;sw")
alias.exact("small!", "nw;sw;se;2s;2e;n;open gate;10e;e;s;10e;2e;n")
alias.exact("small", "s;10w;10w;sw;sw;w;open gate;w;s;2w;2n;nw;ne;se;touch statue")
alias.exact("smithy!", "s;w;3s;w;n")
alias.exact("smithy", "s;e;3n;e;n")
--alias.exact("soprat!", function()
--swim beach;#act {walk up on the beach #delay {1 w;leather!;#unact {walk up on the beach
--end)
alias.exact("soprat", "leather;exit;s;sw;e;swim isle")
alias.exact("soren!", "w;nw;2w;sw;4w;8s;w;n")
alias.exact("soren", "s;e;8n;4e;move leaves;ne;2e;se;e")
alias.exact("spirit!", "e;u;exit;e;s;d;d;s;s;s;s;s;s;e;e;e;e;e;e;e;n")
alias.exact("spirit", "s;w;w;w;w;w;w;w;n;n;n;n;n;n;u;u;n;w;climb stone;move grate;enter hole")
alias.exact("sreyla!", "sw;w;u;e;sisters!")
alias.exact("sreyla", "sisters;w;d;e;ne")
alias.exact("ssword!", "cut net;d;out;w;w;n;n;n;n;e;e;e;e;e;e;n")
alias.exact("ssword", "s;w;w;w;w;w;w;s;s;s;s;e;e;chop tree;enter tree;climb ladder;examine spiderwebs")
alias.exact("sturm!", "s;se;2s")
alias.exact("sturm", "s;w;n;n;n;nw;n;n;n;n;enter;n;n;nw;n")
alias.exact("tartar!", "sw;3e;s;e;2s;2e;5s;w;2s;3w;n")
alias.exact("tartar", "s;3e;2n;e;5n;2w;2n;w;n;3w;ne")
alias.exact("tarzan!", "se;w;s;out;5s;se;5s;w;2s;3w;n")
alias.exact("tarzan", "s;3e;2n;e;5n;nw;5n;enter;n;e;nw")
alias.exact("tempguards!", "day-tempguards!")
alias.exact("tempguards", "day-tempguards")
alias.exact("temple!", "7n;w;n;e;e;n;9e;n")
alias.exact("temple", "s;9w;s;w;w;s;e;7s")
alias.exact("thief!", "2s;w;e;3s;6w;s;2w;6s;w;n")
alias.exact("thief", "s;e;6n;2e;n;6e;3n;w;e;2n")
alias.exact("thjodrek!", "se;s;s;sw;3s;e;s;e;n")
alias.exact("thjodrek", "s;w;n;w;3n;ne;n;n")
alias.exact("tofa!", "n;e;e;e;n;open gate;e;e;e;e;e;e;e;e;e;e;s;e;e;e;e;e;e;e;e;e;e;e;e;n")
alias.exact("tofa", "s;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;s;s;w;w;w;open gate;w;s;w;w;w;open door;s")
alias.exact("toledo!", "w;2s;2w;d;s;3w;2s;2w;2n;5w;4s;w;n")
alias.exact("toledo", "s;e;n;n;n;n;e;e;e;e;e;s;s;e;e;n;n;e;e;e;n;u;e;e;n;n;e")
alias.exact("trink!", "out;n;e;n")
alias.exact("trink", "s;w;s;enter stand")
alias.exact("troll!", "s;s;s;w;w;n;n;w;w;w;w;w;s;s;s;s;w;n")
alias.exact("troll", "s;e;n;n;n;n;e;e;e;e;e;s;s;e;e;n;n;n")
alias.exact("trym!", "w;s;s;e;e;workers!")
alias.exact("trym", "workers;w;w;n;n;e")
alias.exact("tuck!", "sw;enter boat;w;4s;6w;s;2w;6s;w;n")
alias.exact("tuck", "s;e;6n;2e;n;6e;4n;e;enter boat;ne")
alias.exact("uffner!", "d;d;d;d;out;w;n;w;n")
alias.exact("uffner", "s;e;s;e;enter;u;u;u;u")
alias.exact("ularis!", "se;6s;w;n")
alias.exact("ularis", "s;e;6n;nw;jump stones")
alias.exact("vamp!", "s;6u;w;s;e;n")
alias.exact("vamp", "s;w;n;e;6d;n")
alias.exact("vodka!", "w;3s;open gate;10e;s;10e;2e;n")
alias.exact("vodka", "s;10w;7w;2s;2w;2n;w;2w;open gate;w;n;n;n;e")
alias.exact("warden!", "out;e;s;w;s;w;n")
alias.exact("warden", "s;e;n;e;n;w;enter")
alias.exact("wat!", "n;n;n;n;w;w;d;s;w;w;w;s;s;w;w;n;n;w;w;w;w;w;s;s;s;s;w;n")
alias.exact("wat", "s;e;n;n;n;n;e;e;e;e;e;s;s;e;e;n;n;e;e;e;n;u;e;e;s;s;s;s")
alias.exact("welf!", "climb tree;3n;ne;ne;ne;3n;ne;ne;ne;7n;6n;4e;n")
alias.exact("welf", "s;4w;7s;6s;sw;sw;sw;3s;sw;sw;sw;3s;climb tree")
alias.exact("wheal", "wh")
alias.exact("wh", "s;e;n;n;n;n;d;d;d;d;wish healing;u;u;u;u;s;s;s;s;w;n")
alias.exact("wishheal", "wh")
alias.exact("wooden!", "e;3s;6w;2s;3w;n")
alias.exact("wooden", "s;3e;2n;6e;3n;w")
alias.exact("workers!", "e;2s;4e;n")
alias.exact("workers", "s;4w;2n;w")
alias.exact("yamun!", "pip-yamun!")
alias.exact("yamun", "pip-yamun")

-- *** Area ***;

alias.exact("akhilleus!", "3e;5s;7e;n")
alias.exact("akhilleus", "s;7w;5n;3w")
alias.exact("always!", "2s;e;n")
alias.exact("always", "s;w;2n")
alias.exact("anoun!", "3n;10n;4e;n")
alias.exact("anoun", "s;4w;10s;3s")
alias.exact("artemis!", "n;5e;n")
alias.exact("artemis", "s;5w;s")
alias.exact("aza!", "2s;sw;9s;w;n")
alias.exact("aza", "s;e;n;n;n;n;n;n;n;n;n;ne;n;n;w;w;w;w;w;w;w;w;e;n;s;s;n;e;e;e;e")
alias.exact("bael!", "u;sw;7e;n")
alias.exact("bael", "s;7w;ne;d")
alias.exact("bambi!", "sw;7e;n")
alias.exact("bambi", "s;7w;ne")
alias.exact("bannan!", "4s;4e;5s;7e;n")
alias.exact("bannan", "s;7w;5n;4w;4n")
alias.exact("bastard!", "s;6e;n")
alias.exact("bastard", "s;6w;n")
alias.exact("bastista!", "s;9e;n")
alias.exact("bastista", "s;9w;n")
alias.exact("bigdog!", "n;3e;n")
alias.exact("bigdog", "s;3w;s")
alias.exact("boris!", "ne;4w;n")
alias.exact("boris", "s;4e;sw")
alias.exact("brainstorm", "rose;ne;n")
alias.exact("brainstorm!", "s;sw;rose!")
alias.exact("cervus!", "w;7s;w;n")
alias.exact("cervus", "s;e;7n;e")
alias.exact("danny!", "e;s;e;9s;w;n")
alias.exact("danny", "s;e;9n;w;n;w")
alias.exact("day!", "e;s;7e;n")
alias.exact("day", "s;7w;n;w")
alias.exact("digs", "s;3e;2n;e;5n;nw;5n")
alias.exact("digs!", "5s;se;5s;w;2s;3w;n")
alias.exact("dlord!", "n;2e;3s;w;n")
alias.exact("dlord", "s;e;3n;2w;s")
alias.exact("dwarfs!", "n;2n;2w;4s;8e;n")
alias.exact("ferret!", "5s;w;2s;3w;n")
alias.exact("ferret", "s;3e;2n;e;5n")
alias.exact("frogo", "s;e;8n;e")
alias.exact("frogo!", "w;8s;w;n")
alias.exact("frost", "s;9w;n;w")
alias.exact("frost!", "e;s;9e;n")
alias.exact("gaeius!", "2e;2s;2w;s;4e;s;sw;se;3e;s;9e;n")
alias.exact("gaeius", "s;9w;n;3w;nw;ne;n;4w;n;2e;2n;2w")
alias.exact("grumble!", "ashore;4w;n")
alias.exact("grumble", "s;4e;enter ship")
alias.exact("helgrim!", "sw;4w;n")
alias.exact("helgrim", "s;4e;ne")
alias.exact("harlin", "s;7w;3n;2w;n")
alias.exact("harlin!", "s;2e;3s;7e;n")
alias.exact("hellslayer!", "u;4s;w;n")
alias.exact("hellslayer", "s;e;4n;d")
alias.exact("hooker!", "2w;2s;3w;n")
alias.exact("hooker", "s;3e;2n;2e")
alias.exact("iso!", "e;4s;se;5s;w;2s;3w;n")
alias.exact("iso", "s;3e;2n;e;5n;nw;4n;w")
alias.exact("kalishan", "s;7w;enter")
alias.exact("kalishan!", "enter;7e;n")
alias.exact("kalak!", "n;6e;n")
alias.exact("kalak", "s;6w;s")
alias.exact("kihlitt!", "n;2w;n")
alias.exact("kihlitt", "s;2e;s")
alias.exact("klopf!", "w;2s;w;n")
alias.exact("klopf", "s;e;2n;e")
alias.exact("kralk!", "s;sw;4w;n")
alias.exact("kralk", "s;4e;ne;n")
alias.exact("javier", "s;e;n;e")
alias.exact("javier!", "w;s;w;n")
alias.exact("lancelot!", "2n;w;n")
alias.exact("lancelot", "s;e;2s")
alias.exact("loctar", "s;7w;5n;w;nw")
alias.exact("loctar!", "se;e;5s;7e;n")
alias.exact("mares!", "s;cliffs;2n;2w;nw;n;2w;n")
alias.exact("mares", "s;2e;s;se;2e;s;cliffs")
alias.exact("mindbender!", "n;9e;n")
alias.exact("mindbender", "s;9w;s")
alias.exact("mirage!", "s;3w;n")
alias.exact("mirage", "s;3e;n")
alias.exact("mitzelplic!", "4s;w;2s;7e;n")
alias.exact("mitzelplic", "s;7w;2n;e;4n")
alias.exact("monks!", "8s;w;n")
alias.exact("monks", "s;e;8n")
alias.exact("moria!", "w;4s;w;n")
alias.exact("moria", "s;e;4n;e")
alias.exact("mousepad", "s;8w;nw")
alias.exact("mousepad!", "se;8e;n")
alias.exact("mudor!", "w;s;7e;n")
alias.exact("mudor", "s;7w;n;e")
alias.exact("murky!", "s;2d;6s;7e;n")
alias.exact("murky", "s;7w;6n;2u;n")
alias.exact("mysse!", "w;3s;w;n")
alias.exact("mysse", "s;e;3n;e")
alias.exact("nick!", "s;w;s;w;2s;7e;n")
alias.exact("nick", "s;7w;2n;e;n;e;n")
alias.exact("odyssey!", "n;open gate;2n;e;ne;4e;s;7e;n")
alias.exact("odyssey", "s;7w;n;4w;sw;w;s;open gate;2s")
alias.exact("okjuna!", "sw;3w;5s;se;4s;w;2s;3w;n")
alias.exact("okjuna", "s;3e;2n;e;4n;nw;5n;3e;ne")
alias.exact("okkun!", "s;se;e;2s;sw;4w;n")
alias.exact("okkun", "s;4e;ne;2n;w;nw;n")
alias.exact("paladins", "s;10w;w")
alias.exact("paladins!", "10e;e;n")
alias.exact("purple", "s;7w;5n;2e")
alias.exact("purple!", "2w;5s;7e;n")
alias.exact("pendragon!", "s;8e;n")
alias.exact("pendragon", "s;8w;n")
alias.exact("pipe!", "3s;2e;10e;n")
alias.exact("pipe", "s;10w;2w;3n")
alias.exact("powermad!", "w;6s;w;n")
alias.exact("powermad", "s;e;6n;e")
alias.exact("ramoth!", "s;d;6s;7e;n")
alias.exact("ramoth", "s;7w;6n;u;n")
alias.exact("renae!", "se;5s;w;n")
alias.exact("renae", "s;e;5n;nw")
alias.exact("soixanteneuf!", "e;s;e;n")
alias.exact("soixanteneuf", "s;w;n;w")
alias.exact("soular!", "w;5s;w;n")
alias.exact("soular", "s;e;5n;e")
alias.exact("strafe!", "s;5e;n")
alias.exact("strafe", "s;5w;n")
alias.exact("survivor!", "n;e;n;e;n")
alias.exact("survivor-nif!", "nif!")
alias.exact("survivor-nif", "nif")
alias.exact("survivor", "s;w;s;w;s")
alias.exact("tios!", "s;4e;n")
alias.exact("tios", "s;4w;n")
alias.exact("tolpelear!", "enter boat;3w;n")
alias.exact("tolpelear", "s;3e;enter boat")
alias.exact("tundra!", "enter boat;w;4s;6w;s;2w;6s;w;n")
alias.exact("tundra", "s;e;6n;2e;n;6e;4n;e;enter boat")
alias.exact("unschtiaou!", "n;7e;n")
alias.exact("unschtiaou", "s;7w;s")
alias.exact("valcon!", "n;4e;n")
alias.exact("valcon", "s;4w;s")
alias.exact("valiant!", "n;10e;n")
alias.exact("valiant", "s;10w;s")
alias.exact("valinor!", "2w;s;e;s;2d;6s;7e;n")
alias.exact("valinor", "s;7w;6n;2u;n;w;n;2e")
alias.exact("voltron!", "e;s;2e;3s;7e;n")
alias.exact("voltron", "s;7w;3n;2w;n;w")
alias.exact("wonders", "s;3e;2n;2e;6e;d;d;d;d;2n;3e")
alias.exact("wonders!", "3w;2s;u;u;u;u;6w;2w;2s;3w;n")
alias.exact("xodus!", "s;2e;3s;w;n")
alias.exact("xodus", "s;e;3n;2w;n")

-- *** Area Subpaths ***;


-- *** Akhilleus ***;

alias.exact("akh-student", "akhilleus;4w;3n;w")
alias.exact("akh-student!", "e;3s;4e;akhilleus!")
alias.exact("akh-scout", "ethilrist")
alias.exact("akh-scout!", "ethilrist!")
alias.exact("akh-armorer", "seth;w")
alias.exact("akh-armorer!", "e;seth!")
alias.exact("akh-captain", "seth")
alias.exact("akh-captain!", "seth!")
alias.exact("akh-hermit", "akhilleus")
alias.exact("akh-hermit!", "akhilleus!")
alias.exact("akh-chef", "seth;s;e")
alias.exact("akh-chef!", "w;n;seth!")

-- *** Always ***;

alias.exact("alw-skie", "bluedragon")
alias.exact("alw-skie!", "bluedragon!")
alias.exact("alw-deathk", "deathk")
alias.exact("alw-deathk!", "deathk!")

-- *** Anoun ***;

--alias.exact("ano-acha", function()
--anoun;sw;sw;sw;2w;enter;4w;#delay 2 #showme *** GO ALL WEST ***
--end)
alias.exact("ano-acha!", "7e;4e;out;2e;ne;ne;ne;anoun!")
alias.exact("ano-nefer!", "2d;s;open door;2s;3w;2n;ne;ne;ne;anoun!")
alias.exact("ano-nefer", "anoun;sw;sw;sw;2s;3e;2n;open door;n;2u")

-- *** Artemis ***;

alias.exact("art-chamber!", "3e;u;8e;portal;artemis!")

-- *** Azatoths ***;

alias.exact("aza-crone!", "n;aza!")
alias.exact("aza-crone", "aza;s")
alias.exact("aza-ill!", "s;e;s;aza!")
alias.exact("aza-ill", "aza;n;w;n")
alias.exact("aza-inn!", "out;s;aza!")
alias.exact("aza-inn", "aza;n;enter")
alias.exact("aza-old!", "out;n;4e;aza!")
alias.exact("aza-old", "aza;4w;s;enter")
alias.exact("aza-travel!", "3e;s;aza!")
alias.exact("aza-travel", "aza;n;3w")
alias.exact("aza-wench!", "s;aza-inn!")
alias.exact("aza-wench", "aza-inn;n")
alias.exact("aza-priest", "aza;n;2w;s")
alias.exact("aza-priest!", "n;2e;s;aza!")
alias.exact("aza-dwarf", "aza;2e;2n")
alias.exact("aza-dwarf!", "2s;2w;aza!")
--alias.exact("aza-lich", function()
--aza;5w;#echo *** pick plant ***
--end)
alias.exact("aza-lich!", "5e;aza!")

-- *** Bael ***;

alias.exact("bael-castle", "bael;5n;break lock;open door;n")
alias.exact("bael-castle!", "force door open;6s;bael!")

-- *** Bambi ***;

alias.exact("bam-max", "bambi;2n")
alias.exact("bam-max!", "2s;bambi!")
alias.exact("bam-keegan", "bam-max;n;e")
alias.exact("bam-keegan!", "w;s;bam-max!")
alias.exact("bam-sales", "bambi;3n")
alias.exact("bam-sales!", "3s;bambi!")
alias.exact("bam-rich", "bambi;3n;2e")
alias.exact("bam-rich!", "2w;3s;bambi!")
alias.exact("bam-mag", "bambi;4n")
alias.exact("bam-mag!", "4s;bambi!")
alias.exact("bam-jukka", "bambi;5n;2e;enter hut")
alias.exact("bam-jukka!", "out;2w;5s;bambi!")
alias.exact("bam-adv", "bambi;5n;3e;enter")
alias.exact("bam-adv!", "out;3w;5s;bambi!")

-- *** Bastista ***;

alias.exact("bas-cat", "bastista;n;w;nw;n;e;n;enter;pat statue")
alias.exact("bas-cat!", "out;s;w;s;se;e;s;bastista!")
alias.exact("bas-duke", "bas-cat;n;2w")
alias.exact("bas-duke!", "2e;s;bas-cat!")
alias.exact("bas-king", "bas-cat;5n;w")
alias.exact("bas-king!", "e;5s;bas-cat!")
alias.exact("bas-nun", "bas-cat;w")
alias.exact("bas-nun!", "e;bas-cat!")
alias.exact("bas-priest", "bas-cat;2w")
alias.exact("bas-priest!", "2e;bas-cat!")
alias.exact("bas-earl", "bas-cat;3n;e")
alias.exact("bas-earl!", "w;3s;bas-cat!")

-- *** Bigdog ***;

alias.exact("big-king", "mk")
alias.exact("big-king!", "mk!")
alias.exact("big-dragon", "icedragon")
alias.exact("big-dragon!", "icedragon!")
alias.exact("big-thief", "bigdog;enter;3e;turn candlestick;se;e;se")
alias.exact("big-thief!", "nw;w;nw;raise lever;3w;out;bigdog!")

-- *** Cervus ***;

alias.exact("cer-priest", "cervus;n;ne;e;enter forest")
alias.exact("cer-priest!", "out;w;sw;s;cervus!")
alias.exact("cer-guard", "cervus;e")
alias.exact("cer-guard!", "w;cervus!")

-- *** Danny ***;

alias.exact("dan-leiah!", "n;se;3e;s;2e;n;open door;2e;danny!")
alias.exact("dan-leiah", "danny;w;open door;w;s;2w;n;3w;nw;s")
alias.exact("dan-puturo", "dan-leiah;enter")
alias.exact("dan-puturo!", "out;dan-leiah!")
alias.exact("dan-tellis", "danny;s")
alias.exact("dan-tellis!", "n;danny!")
alias.exact("dan-kotro", "danny;n")
alias.exact("dan-kotro!", "s;danny!")
alias.exact("dan-practicer", "danny;3n;w;open gate;n")
alias.exact("dan-practicer!", "open gate;s;e;3s;danny!")

-- *** Day ***;

alias.exact("day-tempguards", "day;w;2n")
alias.exact("day-tempguards!", "2s;e;day!")
alias.exact("day-goblin", "day;3w;sw;2w;n")
alias.exact("day-goblin!", "s;2e;ne;3e;day!")

-- *** Ferret ***;

alias.exact("fer-dacian", "ferret;s;nw;w;sw;ne;ne;n;ne;ne;ne")
alias.exact("fer-dacian!", "sw;sw;sw;s;sw;sw;ne;e;se;n;ferret!")
alias.exact("fer-slavic", "ferret;s;nw;w;sw")
alias.exact("fer-slavic!", "ne;e;se;n;ferret!")
alias.exact("fer-khan", "ferret;s;nw;w;4n;nw;2w;n")
alias.exact("fer-khan!", "s;2e;se;4s;e;se;n;ferret!")
alias.exact("fer-xanadu", "ferret;nw;4n;5e")
alias.exact("fer-xanadu!", "5w;4s;se;ferret!")
alias.exact("fer-owner", "fer-xanadu;4e;2s;e")
alias.exact("fer-owner!", "w;2n;4w;fer-xanadu!")
alias.exact("fer-egs", "fer-xanadu;6e;say please me")
alias.exact("fer-egs!", "7w;fer-xanadu!")

-- *** Frogo ***;

alias.exact("fro-luci", "frogo;2e;2n;open door;enter;n;elevator")
alias.exact("fro-luci!", "exit;s;exit;2s;2w;frogo!")
alias.exact("fro-dleader", "frogo;7e;la opening;la fold;open fold;enter;exa zipper;open zipper")
alias.exact("fro-dleader!", "la zipper;open zipper;exit;7w;frogo!")
alias.exact("fro-tree", "frogo;4e;enter")
alias.exact("fro-tree!", "exit;4w;frogo!")
alias.exact("fro-bank", "")
alias.exact("fro-bank!", "")

-- *** Gaeius ***;

alias.exact("gae-inn!", "open door;3e;3s;2e;se;e;gaeius!")
alias.exact("gae-inn", "gaeius;w;nw;2w;3n;2w;open door;w")
alias.exact("gae-jonas!", "e;gae-inn!")
alias.exact("gae-jonas", "gae-inn;w")
alias.exact("gae-keshute", "ruin;ne;n;w;2s")
alias.exact("gae-keshute!", "2n;e;s;sw;ruin!")
alias.exact("gae-ustmor", "gae-inn;2e")
alias.exact("gae-ustmor!", "2w;gae-inn!")
alias.exact("gae-troll", "gaeius;w;nw;2w;3n;2e;5n;e;n;2w")
alias.exact("gae-troll!", "2e;s;w;5s;2w;3s;2e;se;e;gaeius!")
alias.exact("gae-orc", "gaeius;w;nw;2w;3n;2e;5n;e;n;ne;2n;nw;ne;ne;e;ne;e")
alias.exact("gae-orc!", "w;sw;w;sw;sw;se;2s;sw;s;w;5s;2w;3s;2e;se;e;gaeius!")
--alias.exact("gae-smurf", function()
--s;3w;s;enter;2w;shrink;#delay 2 #showme *** north, enter crack ***
--end)
alias.exact("gae-smurf!", "enter crack;s;out;2e;out;n;2e;n")
alias.exact("gae-paxitus", "s;w;s;se")
alias.exact("gae-paxitus!", "nw;n;e;n")

-- *** Grumble ***;

alias.exact("gru-igor", "grumble")
alias.exact("gru-igor!", "grumble!")

-- *** Helgrim ***;

alias.exact("hel-smith", "helgrim;2e;enter")
alias.exact("hel-smith!", "out;2w;helgrim!")
alias.exact("hel-flugeluff", "helgrim;2e;u;u;u;open door;enter;search debris;enter hole")
alias.exact("hel-flugeluff!", "search wall;pull block;enter tunnel;left;right;right;right;d;2w;helgrim!")

-- *** Hellslayer ***;

alias.exact("hell-hablar", "hellslayer")
alias.exact("hell-hablar!", "hellslayer!")

-- *** Hooker ***;

alias.exact("hoo-grendel!", "out;e;d;2s;w;hooker!")
alias.exact("hoo-grendel", "hooker;e;2n;u;w;in")
alias.exact("hoo-king!", "nestor!")
alias.exact("hoo-king", "nestor")
alias.exact("hoo-pilgrim!", "5s;2e;5s;4w;hooker!")
alias.exact("hoo-pilgrim", "hooker;4e;5n;2w;5n")
alias.exact("hoo-serpent!", "u;e;s;d;2s;w;hooker!")
alias.exact("hoo-serpent", "hooker;e;2n;u;n;w;d")
alias.exact("hoo-nymph", "hooker;4e;5n;2w;3n;grove")
alias.exact("hoo-nymph!", "out;3s;2e;5s;4w;hooker!")
alias.exact("hoo-barbarian", "s;3e;2n;e;3n;2w;2s")
alias.exact("hoo-barbarian!", "2n;2e;3s;w;2s;3w;n")

-- *** Iso ***;

alias.exact("iso-church", "iso;3n;2e")
alias.exact("iso-church!", "2w;3s;iso!")

-- *** Kalishan ***;

alias.exact("kal-keeper", "kalishan;2u;e;2s;w")
alias.exact("kal-keeper!", "e;2n;w;2d;kalishan!")

-- *** Mindbender ***;

alias.exact("min-draco", "mindbender;2w;s;2w;10s;d;d")
alias.exact("min-draco!", "u;u;10n;2e;n;2e;mindbender!")

-- *** Monks ***;

alias.exact("mon-molsen", "monks;2n;climb cliffs;2s")
alias.exact("mon-molsen!", "2n;climb cliffs;2s;monks!")
alias.exact("mon-manion", "monks;2n;climb cliffs;3s")
alias.exact("mon-manion!", "3n;climb cliffs;2s;monks!")

-- *** Moria ***;

alias.exact("mor-pass", "moria;4e;2s;2e;2n;3e;2s;e;say mellon")
alias.exact("mor-pass!", "w;2n;3w;2s;2w;2n;4w;moria!")
alias.exact("mor-kneel!", "3w;2s;10e;enter curtain;2w;n")
alias.exact("mor-kneel", "e;2u;e;2n;3e")

-- *** Mousepad ***;

alias.exact("mos-shaft-bottom", "tunnel;4e;se;se;8s;swim;downstream;upstream;upstream;ashore;climb")
alias.exact("mos-shaft-bottom!", "climb;swim;swim;ashore")
--alias.exact("mos-shaft", function()
--mousepad;#10 {mos-shaft-bottom;#12 u;enter;swim;swim;swim;ashore mos-shaft-bottom;#12 u;swim;swim;swim;ashore
--end)
alias.exact("mos-shaft!", "ne;ne;ne;ne;ne;out;climb;mousepad!")
alias.exact("mos-light", "mousepad;tunnel;4e;se;se;8s;swim;downstream;upstream;upstream;climb;get all;tag crystal;d;ashore;climb;mos-shaft-bottom!;mousepad!")

-- *** Nick ***;

alias.exact("nic-castle", "nick;3n;2e;n;e;n")
alias.exact("nic-castle!", "s;w;s;2w;3s;nick!")
alias.exact("nic-knight", "nick;n;2e;ne;e")
alias.exact("nic-knight!", "w;sw;2w;s;nick!")
alias.exact("nic-hermit", "nick;n;2e;2n;2e")
alias.exact("nic-hermit!", "2w;2s;2w;s;nick!")

-- *** Odyssey ***;

alias.exact("ody", "odyssey")
alias.exact("ody!", "odyssey!")
alias.exact("ody-bank!", "n;e;3n;odyssey!")
alias.exact("ody-bank", "odyssey;3s;w;s")
alias.exact("ody-dwarf!", "open south door;s;2e;odyssey!")
alias.exact("ody-dwarf", "odyssey;2w;open north door;n")
alias.exact("ody-ladder!", "open north door;n;2e;7n;odyssey!")
alias.exact("ody-ladder", "odyssey;7s;2w;open south door;s")
alias.exact("ody-mayor!", "out;w;7n;odyssey!")
alias.exact("ody-mayor", "odyssey;7s;e;enter")
alias.exact("ody-ngate!", "open gate;2s;odyssey!")
alias.exact("ody-ngate", "odyssey;n;open gate;n")
alias.exact("ody-pot!", "n;e;odyssey!")
alias.exact("ody-pot", "odyssey;w;s")
alias.exact("ody-sgate!", "open gate;10n;odyssey!")
alias.exact("ody-sgate", "odyssey;9s;open gate;s")
alias.exact("ody-soldiers!", "open south door;s;e;7n;odyssey!")
alias.exact("ody-soldiers", "odyssey;7s;w;open north door;n")

-- *** Okjuna ***;

alias.exact("okj-leather", "okjuna;2n;e;ne;n;enter cabin")
alias.exact("okj-leather!", "exit;s;sw;w;2s;okjuna!")

-- *** Paladin ***;

alias.exact("pal-elitan", "fake good;atli;open gate;w;s;4w;n;open door;w")
alias.exact("pal-elitan!", "open door;e;s;4e;n;open gate;e;atli!")
alias.exact("pal-thjodek", "fake good;atli;open gate;w;2n;open door;e")
alias.exact("pal-thjodek!", "open door;w;2s;open gate;e;atli!")
alias.exact("pal-melnir", "fake good;atli;open gate;w;s;2w;2n;nw;w")
alias.exact("pal-melnir!", "e;se;2s;2e;n;open gate;e;atli!")
alias.exact("pal-tofa", "fake good;atli;open gate;w;s;3w;open door;s")
alias.exact("pal-tofa!", "open door;n;3e;n;open gate;e;atli!")

-- *** Pipe ***;

alias.exact("pip-ragnar", "pipe;n")
alias.exact("pip-ragnar!", "s;pipe!")
alias.exact("pip-yamun", "pipe;e;ne;ne;ne;enter")
alias.exact("pip-yamun!", "out;sw;sw;sw;w;pipe!")

-- *** Roo ***;

alias.exact("roo-abbey", "safe-forest;4s")
alias.exact("roo-abbey!", "4n;safe-forest!")
alias.exact("roo-mother", "safe-forest;5s;3e")
alias.exact("roo-mother!", "3w;5n;safe-forest!")

-- *** Soular ***;

alias.exact("sou-lady", "soular;n")
alias.exact("sou-lady!", "s;soular!")

-- *** Strafe ***;

alias.exact("str-knight", "strafe;2n;w;n;ne;2w;2n;w;2n")
alias.exact("str-knight!", "2s;e;2s;2e;4s;strafe!")

-- *** Tios ***;

alias.exact("tio-mayor", "tios;n;w;2n")
alias.exact("tio-mayor!", "2s;e;s;tios!")
alias.exact("tio-eugene", "tios;n;w;n")
alias.exact("tio-eugene!", "s;e;s;tios!")

-- *** Ulari ***;

alias.exact("ula-stag1", "2n;e;ne")
alias.exact("ula-stag1!", "sw;w;2s")
alias.exact("ula-stag2", "n;2w;nw;n;move fern;ne;2e")
alias.exact("ula-stag2!", ";2w;sw;s;se;2e;s")
alias.exact("ula-kurak", "3n;4w")
alias.exact("ula-kurak!", "e;4s")
alias.exact("ula-bag", "n;2w;nw;w")
alias.exact("ula-bag!", "e;se;2e;s")
alias.exact("ula-reptile", "n;2w;nw;n;move ferns;ne;2e;sw;w")
alias.exact("ula-reptile!", "e;ne;2w;sw;s;se;2e;s")
alias.exact("ula-tarrock", "n;2w;nw;n;move ferns;ne;2e;n;ne;se;drop log;push log into lake;leap island")
alias.exact("ula-shagul", "n;2w;nw;n;move ferns;ne;2e;n;ne;se;s;enter")
alias.exact("ula-shagul!", "out;n;nw;sw;s;2w;sw;s;se;2e;s")


-- *** Unschtiaou ***;

alias.exact("uns-mother", "unschtiaou;open door;in;u")
alias.exact("uns-mother!", "d;open door;out;unschtiaou!")

-- *** Voltron ***;

alias.exact("vol-old", "voltron;3w;2n;2w;n")
alias.exact("vol-old!", "s;2e;2s;3e;voltron!")

-- *** Continent Paths ***;


-- *** Amril ***;

alias.exact("abake!", "out;6w;6w;enter")
alias.exact("abake", "out;6e;6e;enter")
alias.exact("abank!", "out;n;n;enter")
alias.exact("abank", function()

end)
alias.exact("abar!", "w;s;out;4n;7w;4n;6w;enter")
alias.exact("abar", "out;6e;4s;7e;4s;enter;n;e")
alias.exact("acastle!", "out;2e;4n;7w;nw;nw;nw;nw;dock;adock!")
alias.exact("acastle", function()

end)
alias.exact("acent!", "5w;8s;5w;5s;10s;6w;enter")
alias.exact("acent", "out;6e;10n;5n;5e;8n;5e")
alias.exact("adock!", "back;se;se;se;se;10e;n;e;10e;10e;4s;6w;enter")
alias.exact("adock", "out;6e;4n;10w;10w;w;s;10w;nw;nw;nw;nw;dock")
alias.exact("alars!", "altar;rs;astone!")
alias.exact("alars", "astone;rs;altar!")
alias.exact("apot!", "out;6w;2n;6w;enter")
alias.exact("apot", "out;6e;2s;6e;enter")
alias.exact("astone!", "out;4e;8n;2n;enter")
alias.exact("astone", "out;2s;8s;4w;enter")
alias.exact("atol!", "out;2e;4s;8e;4s;6e;4s;6w;enter")
alias.exact("atol", "out;6e;4n;6w;4n;8w;4n;2w;enter")
alias.exact("avil", "out;6e;6n;10w;2n;4w;3n;ne;2n;10w")
alias.exact("avil!", "10e;2s;sw;3s;4e;2s;10e;6s;6w;enter")
alias.exact("aliz", "out;6e;6n;10w;2n;4w;3n;ne;3n;ne;ne;ne;9e;ne;ne;ne;3e;ne;ne;ne;3n;4w;2n")
alias.exact("aliz!", "2s;4e;3s;sw;sw;sw;3w;sw;sw;9w;sw;sw;sw;3s;sw;3s;4e;2s;10e;6s;6w;enter")
alias.exact("atower!", "d;w;7n;10e;e;6s;6w;enter")
alias.exact("atower", "out;6e;6n;10w;w;7s;e;climb")
alias.exact("ashaman", "out;6e;6n;10w;w;6s;7w;s;e")
alias.exact("ashaman!", "w;n;7e;6n;e;10e;6s;6w;enter")
alias.exact("adwarf", "out;6e;4n;6w;4n;8w;4n;3n;ne;ne;ne;n;w;10w;s;9w;7n;4e;enter")
alias.exact("adwarf!", "out;4w;7s;9e;n;10e;e;s;sw;sw;sw;3s;4s;8e;4s;6e;4s;6w;enter")
alias.exact("asludge!", "u;9w;8s;6w;enter")
--alias.exact("asludge", function()
--out;6e;8n;9e;d;#delay 2 #showme *** search slime, pull rock, wipe slime, pull twig ***
--end)
alias.exact("amist!", "out;5n;2w;enter;atol!")
alias.exact("amist", "atol;out;2e;5s;enter")
alias.exact("atroll", "out;6e;2n;10n;10n;ne;6e;3n;7w;3n;6w;enter")
alias.exact("atroll!", "out;6e;3s;7e;3s;6w;sw;10s;10s;2s;6w;enter")

-- *** Empire ***;

alias.exact("empire", "s;4e;altdorf;enter ship;n;3w;2n;e;n;e;n;2e;3n;4w;s;3w;s")
alias.exact("empire!", "n;3e;n;4e;3s;2w;s;w;s;w;2s;3e;s;larstown;4w;n")
alias.exact("esmith", "n;3e;n;3e;4n;10e;2e;s;5e;2s;w;s;2w;s;3w;n;w;n")
alias.exact("esmith!", "s;e;s;3e;n;3e;n;e;2n;5w;n;2w;10w;4s;3w;s;3w;s")
alias.exact("edock", "n;3e;n;4e;3s;2w;s;w;s;w;2s;3e;s")
alias.exact("edock!", "n;3w;2n;e;n;e;n;2e;3n;4w;s;3w;s")
alias.exact("ecity", "altdorf;3e;n;8e;s;e;s;4e;2s;e;s;2e;s;5e;s;4e;2n;e;4n;3e;5n;2e;2n;3e;4n;3e;s;edock!")
alias.exact("ecity!", "edock;n;3w;4s;3w;2s;2w;5s;3w;4s;w;2s;4w;n;5w;n;2w;n;w;2n;4w;n;w;n;8w;s;4w")
alias.exact("eblack", "ecity!;6n;e;10e;5n;10n;10w;8n;10w;4n;blackrock")
alias.exact("eblack!", "out;4s;10e;8s;10e;10s;5s;10w;w;6s;ecity")
alias.exact("ereidar", "n;3e;n;4e;3s;2w;s;w;s;w;6s;3w;2s;2w;s;5w;s;w;2s;2w;2s;e")
alias.exact("ereidar!", "w;2n;2e;2n;e;n;5e;n;3e;2n;3e;6n;e;n;e;n;2e;3n;4w;s;3w;s")

-- *** From Outside City ***/
alias.exact("elair", "10n;10e;10n;5w;4n;10w;6n;10w;nw;2w;nw;nw;3n;lair")
alias.exact("elair!", "out;3s;se;se;2e;se;10e;6s;10e;4s;5e;10s;10w;10s")

-- *** Reikland ***;

alias.exact("rbank!", "3n;3w;3s;5w;s")
alias.exact("rbank", "n;5e;3n;3e;3s")
alias.exact("rdock!", "s;se;se;6e;10s;2s;5w;s")
alias.exact("rdock", "n;5e;2n;10n;6w;nw;nw;n")
alias.exact("rfb!", "5n;10w;3s;6w;s")
alias.exact("rfb", "n;6e;3n;10e;5s")
alias.exact("rpot!", "7w;2n;5w;s")
alias.exact("rpot", "n;5e;2s;7e")
alias.exact("rsmith!", "3e;3s;7e;3s;5w;s")
alias.exact("rsmith", "n;5e;3n;7w;3n;3w")
alias.exact("rdwarf", "n;5e;4s;10e;5e")
alias.exact("rdwarf!", "5w;10w;4n;5w;s")
alias.exact("rhut", "n;5e;3n;10w;s;se;se;sw;sw;2w")
alias.exact("rhut!", "2e;ne;ne;nw;nw;n;10e;3s;5w;s")


-- *** Soblak ***;

alias.exact("sdragshop!", "e;7s;d;4s;se;e;s;sw;3s;sw;s;e;2s;se;e;2s;sw;sw;3s;sw;s;se;se;e;se;s;sw;3s")

-- *** Larstown Freebies ***;

alias.exact("fr", "f1;f2;f3;f4;f5;f6;f7;f8;f9;f10;f11;f12;f13")
alias.exact("f1", "s;e;s;e;n;w;enter;s;get all from vase;u;n;get all from bookcase;s;d;n;out;e;s;w;n;w;n;sell all")
alias.exact("f3", "bkgolem;d;d;get urn;get key from urn;unlock door;open door;s;move block;get chest;n;u;u;bkgolem!;toss silver key;sell all")
alias.exact("f6", "workers;w;s;dig sand;get coin;n;e;workers!")
--alias.exact("f4", function()
--s;e;4n;5e;3s;w;#10 get rock;e;3n;5w;4s;w;n;sell all;toss stone
--end)
alias.exact("f2", "elfs;d;get all from bookcase;u;elfs!;sell all")
alias.exact("f5", "s;3e;n;get all;s;3w;n;sell all")
alias.exact("f7", "sisters;n;2w;take all;e;s;d;ne;take all;sw;u;e;sisters!;sell all")
alias.exact("f8", "kodiac;out;w;2n;climb tree;get all;climb down;2s;e;enter;kodiac!;sell all")
alias.exact("f9", "mirror;climb;s;u;get all;d;n;enter;mirror!;sell all")
alias.exact("f10", "s;e;4n;5e;2s;2e;2n;3e;n;u;2e;touch statue;get all;2w;d;s;3w;2s;2w;2n;5w;4s;w;n;sell all")
alias.exact("f11", "s;7w;enter;2u;e;2s;w;n;search;get all;s;e;2n;w;2d;enter;7e;n;sell all")
alias.exact("f12", "s;9w;2n;w;nw;n;e;n;enter;2d;w;n;search moss;s;e;2u;out;s;w;s;se;e;2s;9e;n;sell all")
alias.exact("f13", "s;w;3n;nw;3n;u;get all;d;3s;se;3s;e;n;sell all")
alias.exact("miners", "rose;ne;n;nw;b;gab;n;b;gab;n;b;gab;w;b;gab;nw;b;gab;se;s;b;gab;sw;b;gab;ne;e;b;gab;s;b;gab;se;s;sw;rose!;sa")

-- *** Safe House ***;


--/* Public */
alias.exact("safe", "safe-forest;safe-walk;safe-tree")
alias.exact("safe!", "safe-tree!;safe-walk!;safe-forest!")
alias.exact("safe-walk", "u;w;n;6e;w;n;6e;w;n;6e;w;n;6e;w;n;6e;w;n;6e;w;n;6e;w;n;ne")
alias.exact("safe-walk!", "sw;6s;4n;e;6s;4n;e;6s;4n;e;6s;4n;e;6s;4n;e;6s;4n;e;d")
alias.exact("safe-tree", "2e;ne;n;enter tree")
alias.exact("safe-tree!", "out;s;sw;2w")
alias.exact("safe-forest", "rope-shaft;2w;3n;w;nw;ne;n;u")
alias.exact("safe-forest!", "d;s;e;d;s;sw;se;e;3s;2e;rope-shaft!")

--/* Private */
alias.exact("sh", "s;e;s;s;enter safehouse")
alias.exact("sh!", "out;n;n;w;n")

-- *** Broken Paths (Requires Fixing)  ***;

alias.exact("adventurer!", "2e;se;e;3s;2e;5s;bdp!")
alias.exact("adventurer", "bdp;5n;2w;3n;w;nw;2w")
alias.exact("balrog!", "2s;3u;e;n;w;2n;2w;wimpy 0;w;take log;wimpy 100;6w;3s;w;n")
alias.exact("balrog", "s;e;3n;6e;wimpy 0;drop log;e;wimpy 100;2e;2s;e;s;w;3d;2n")
alias.exact("dark!", "d;s;s;e;e;e;e;s;s;d;d;s;s;u;e;d;d;s;s;s;s;s;s;e;e;e;e;e;e;e;n")
alias.exact("dark", "s;w;w;w;w;w;w;w;n;n;n;n;n;n;u;u;w;d;n;n;u;u;n;n;w;w;w;w;n;n;u")
alias.exact("dkguards!", "d;6s;4w;2s;2d;2s;u;e;2d;6s;7e;n")
alias.exact("dkguards", "s;7w;6n;2u;w;d;2n;2u;2n;4e;6n;u")
alias.exact("docworkers!", "2s;w;sw;8s;2e;5s;bdp!")
alias.exact("docworkers", "s;7w;5n;2w;8n;ne;e;2n")
alias.exact("dworkers!", "out;3w;4s;2e;5s;7e;n")
alias.exact("dworkers", "s;7w;5n;2w;4n;3e;enter waterfall;look")
alias.exact("engi!", "out;w;2s;w;arena!")
alias.exact("engi", "arena;e;2n;e;enter")
alias.exact("gnomer!", "2u;2s;out;2s;e;n")
alias.exact("gnomer", "s;w;2n;enter;2n;2d")
alias.exact("hob!", "10s;2s;7e;n")
alias.exact("hob", "s;7w;5n;2e;4u")
alias.exact("lking!", "s;e;3s;e;u;out;2e;4n;6e;n")
alias.exact("lking", "s;6w;4s;2w;exa huge tree;wield axe;chop tree;enter hole;d;e;3n;w;n")
alias.exact("strahd!", "exit;e;2n;2w;2s;w;3n;w;n")
alias.exact("strahd", "s;e;3s;e;2n;2e;2s;w;enter")
alias.exact("marvin!", "sw;s;s;s;s;s;s;s;s;s;e;e;s;s;s;s;s;e;e;e;e;e;e;e;n")
alias.exact("marvin", "s;w;w;w;w;w;w;w;n;n;n;n;n;w;w;n;n;n;n;n;n;n;n;n;ne")
alias.exact("medusa!", "w;2n;u;s;e;5s;2e;3s;w;n")
alias.exact("medusa", "s;e;3n;3w;5n;w;move bench;climb bench;pull chain;climb down;move")
alias.exact("norbin!", "sw;2s;2e;6s;2e;5s;7e;n")
alias.exact("norbin", "s;7w;5n;2w;6n;2w;2n;ne")
alias.exact("phoenix!", "sw;7w;s;7e;n")
alias.exact("phoenix", "s;7w;n;7e;ne")
alias.exact("pill!", "n;w;5s;w;n")
alias.exact("pill", "s;e;5n;e;s")
alias.exact("richter!", "examine pool;press button;s;out;e;n;n;w;w;s;s;w")
alias.exact("richter", "e;n;n;e;e;s;s;w;w;open gate;n;move tiles")
alias.exact("stower!", "e;s;s;s;s;s;s;s;s;s;s;e;e;s;s;s;s;s;e;e;e;e;e;e;e;n")
alias.exact("stower", "s;w;w;w;w;w;w;w;n;n;n;n;n;w;w;n;n;n;n;n;n;n;n;n;n;w")
alias.exact("xna!", "u;5s;w;s;6w;5s;3w;enter ship;3w;n")
alias.exact("xna", "s;3e;enter ship;4e;2n;6e;n;e;3n;d")

runes.output("VK Loaded!")
